### ISSUE TITLE
Secp Hints

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/cairo-vm_in_go#203]
This requires first implementing `secp_utils` (See [here](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/cairo_secp/secp_utils.py) and [here](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/secp/secp_utils.rs)) 

List:

- [x] `NONDET_BIGINT3_V1`
- [ ] `BIGINT_TO_UINT256` #309 
- [ ] `VERIFY_ZERO_V1` #307 
- [ ] `IS_ZERO_NONDET` #309
- [ ] `IS_ZERO_PACK_V1` #309
- [ ] `IS_ZERO_ASSIGN_SCOPE_VARS` #309
- [ ] `REDUCE_V1` #307
